#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases
alias zconf="code $HOME/.zshrc"
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"

# n - node version manager
export N_PREFIX=$HOME/.n
export PATH="$N_PREFIX/bin:$PATH"

# jenv - java version manager
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
